version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    depends_on:
      db:
    container_name: backend_prod
    image: goldreborn/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    container_name: frontend_prod
    image: goldreborn/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    depends_on:
      backend:
        condition: service_started
    container_name: nginx_prod
    image: goldreborn/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/media
    ports:
      - 9000:80